### ISSUE TITLE
Templates not found on OSX

### ISSUE THREAD

**Issue by ghost** [sleipnir/cloudstate-cli#13]
**Describe the bug**
When running `cloudstate create ...` on OSX I get an exception.  The templates directory appears empty, assuming that's the cause.

**To Reproduce**
1. Install cloudstate-cli 0.4.0
2. `cloudstate create --name=shopping-cart --profile=csharp`

**Expected behavior**
Shopping cart app created

**Screenshots**
shell output below
```
Creating user function project: "shopping-cart"
Using profile: "csharp"
Extracting profile template.... /Users/jnagy/.cloudstate/templates/csharp/csharp.tar.gz
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1189:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Checking cloudstate directory...
```
nagytech-2:bin jnagy$ cd ~/.cloudstate/
nagytech-2:.cloudstate jnagy$ ls
nagytech-2:.cloudstate jnagy$ ls -al
total 0
drwxr-xr-x   2 jnagy  staff    64 23 Nov 19:47 .
drwxr-xr-x+ 73 jnagy  staff  2336 30 Nov 07:50 ..
nagytech-2:.cloudstate jnagy$ 
```

**Comment by sleipnir** [comment]
You must first use cloudstate init to have it download and configure the required environment. I recommend you follow the steps described in the Readme.
It may make sense to remove this step in the future, but for now it would be interesting to consider it.
I will leave notes here to better handle the error message to the user.
Let me know if this helped you

**Comment by sleipnir** [comment]
Try:
cloudstate create \
  --name=shopping-cart \
  --profile=csharp \
  --registry=docker.io/your_repo \
  --set-user=your_user \
  --set-pass=your_pass \
  --tag=1.0.1 \
  --set-editor=code

**Comment by ghost** [comment]
Got it working, thanks.
