### ISSUE TITLE
Unix cross-platform Completions directory

### ISSUE THREAD

**Issue by ghost** [sleipnir/cloudstate-cli#9]
The `cloudstate-installer.sh` script attempts to install the CloudState completions into: `/etc/bash_completion.d/cloudstate.bash-completion`.  But, on my local machine (OSX) I have installed bash_completion via homebrew which exists at: `/usr/local/etc/bash_completion.d`.

I have a few ideas on how to support different installation flows on different OS, let me know if something doesn't mesh with what you already have in mind.

**Comment by sleipnir** [comment]
Hi @nagytech .
I believe the current script and installation is very poor, there is a lot of room for improvement, there is already a TODO in the script indicating that there are things to be done. Feel free to suggest as many improvements as you wish, unfortunately I believe that the cloudstate cli binary itself would only be compatible in the short term with Linux and MacOS systems. For windows a number of other issues will have to be reviewed for it to work accordingly. So it might be interesting to focus on these two starting platforms and then adding support there are other systems and architectures

**Comment by sleipnir** [comment]
Closed #10
